E-shop/shopping_mall/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<product_id>/', views.cart_delete, name='cart_delete'),
]

E-shop/shopping_mall/shopping_mall/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import logout, RegisterView,LoginView
from contact import views as contact_views
from mall.views import SearchFormView
from mall.views import MainView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mall.urls')),
    path('product/', include('product.urls')),
    path('logout/', logout),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('contact/', contact_views.contact_view, name='contact'),
    path('cart/', include('cart.urls')),
    path('search/', SearchFormView.as_view(), name='search'),
]
    

E-shop/shopping_mall/cart/models.py
from django.db import models
from user.models import User
from product.models import Item
from user.models import User
import random
# Create your models here.
class MfRecommend(models.Model):
    recommend_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, models.DO_NOTHING, blank=True, null=True)
    recommend = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mf_recommend'

class Cart(models.Model):
    # cart_id = models.CharField(max_length=250, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        #return self.cart_id
        return (str(self.user) + ' ' + str(self.cart_id))

    def get_mf_recommend(self):
        user = User.objects.get(email_id=self.user.email_id)
        recommend = MfRecommend.objects.get(user_id=user).recommend[1:-1].split(",")
        recommends = []
        cnt = 0
        for r in recommend:
            cnt += 1
            recommends.append(Item.objects.get(asin=r))
            if cnt == 5:
                break

        return recommends

class CartItem(models.Model):
    product = models.ForeignKey(Item, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    # 수량은 -1 과 같은 수량이 없기 때문에 아래의 필드로 선언하여 최소값을 1 로 설정
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return round(float(self.product.price) * self.quantity, 2)

    def __str__(self):
        return self.product

E-shop/shopping_mall/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Item
from user.models import User
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
# def _cart_id(request):
#     #cart = request.session.session_key
#     user = User.objects.get(email=request.session.get('user'))
#     cart = Cart.objects.get(user=user)
#     if not cart:
#         cart = request.session.create()
#     return cart

def add_cart(request, product_id):
    product = Item.objects.get(asin=product_id)
    try:
        user = User.objects.get(email=request.session.get('user'))
        #cart = Cart.objects.get(cart_id=_cart_id(request), user=user)
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        user = User.objects.get(email=request.session.get('user'))
        cart = Cart.objects.create(
            user = user,
            # cart_id = _cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    #return render(request, 'product/list.html')
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        user = User.objects.get(email=request.session.get('user'))
        # cart = Cart.objects.get(cart_id=_cart_id(request), user=user)
        cart = Cart.objects.get(user=user)
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (float(cart_item.product.price) * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    if counter > 0:
        total += 5

    try:
        return render(request, 'cart/cart.html', dict(cart_items = cart_items, total=round(total,2), counter=counter, cart=cart))
    except:
        return render(request, 'cart/cart.html', dict(cart_items = cart_items, total=round(total,2), counter=counter))

def cart_remove(request, product_id):
    user = User.objects.get(email=request.session.get('user'))
    # cart = Cart.objects.get(cart_id = _cart_id(request), user=user)
    cart = Cart.objects.get(user=user)
    product = get_object_or_404(Item, asin=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def cart_delete(request, product_id):
    user = User.objects.get(email=request.session.get('user'))
    cart = Cart.objects.get(user=user)
    product = get_object_or_404(Item, asin=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity:
        cart_item.delete()

    return redirect('cart:cart_detail')

E-shop/shopping_mall/cart/templates/cart/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}
</head>
{% block error %}
{% endblock %}
<body>
    <!-- Navbar -->
    {% include  'mall/navbar.html' %}

    {% block contents %}
    {% endblock %}

    <!-- footer -->
    {% include 'mall/footer.html' %}
    <!--/.Footer-->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>
</body>

</html>

E-shop/shopping_mall/cart/templates/cart/cart.html
{% extends "cart/base.html" %}
{% load humanize %}
{% load static %}
{% block header %}
	<meta name="author" content="Graduate">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
	<!-- Bootstrap core CSS -->
	<link href="{% static '/css/bootstrap.css' %}" rel="stylesheet">
	<!-- Material Design Bootstrap -->
	<link href="{% static '/css/mdb.css' %}" rel="stylesheet">
	<!-- Your custom styles (optional) -->
	<link href="{% static '/css/style.css' %}" rel="stylesheet">
	<link href="{% static '/css/cart_style.css' %}" rel="stylesheet">
	<title>DAGO Mall</title>
{% endblock %}

{% block error %}
<div class="row mt-5">
    <div class="col-12 text-center">
        {{error}}
    </div>
</div>
{% endblock %}

{% block contents %}
<div class="main-body">
    <div class="card">
        <div class="row">
            <div class="col-md-8 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h4><b>Shopping Cart</b></h4>
                        </div>
                        <div class="col align-self-center text-right text-muted">{{cart_items.count}} Item(s)</div>
                    </div>
                </div>
                <div class="row border-top border-bottom">
                    {% for cart_item in cart_items %}
                    <div class="row main align-items-center">
                        {% if cart_item.product.get_image_link %}
                        {% if cart_item.product.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
                        <a class="col-2" href="{{cart_item.product.get_absolute_url}}"><img class="img-item" height="50px" src="{{cart_item.product.get_image_link}}"></a>
                        {% else %}
                        <a class="col-2" href="{{i.get_absolute_url}}"><img class="img-item" height="50" src="{% static '/img/no_image.png' %}"></a>
                        {% endif %}
                        {% else %}
                        <a class="col-2" href="{{i.get_absolute_url}}"><img class="img-item" height="50" src="{% static '/img/no_image.png' %}"></a>
                        {% endif %}
                        <div class="col">
                            <a class="row" href="{{cart_item.product.get_absolute_url}}">{{cart_item.product.title | truncatechars:30}}</a>
                        </div>
                        <div class="col"> <a href="{% url 'cart:add_cart' cart_item.product.asin %}">+</a><a href="#" class="border">{{cart_item.quantity|intcomma}}</a><a href="{% url 'cart:cart_remove' cart_item.product.asin %}">-</a></div>
<!--                        <div class="col">price : {{cart_item.product.price}} </div>-->
                        <div class="col">total : {{cart_item.sub_total}}</div>
                        <div class="col"><a class="close right" href="{% url 'cart:cart_delete' cart_item.product.asin %}">&#10005;</a></div>
                    </div>
                    {% endfor %}
                    <div class="col"></div>
                </div>
                <div class="back-to-shop"><a href="#" onclick="location.href='/'">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
            </div>
            <div class="col-md-4 summary">
                <div>
                    <h5><b>Summary</b></h5>
                </div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:0;">TOTAL ITEM(S) {{counter}}</div>
                </div>
                <form>
                    <p>SHIPPING</p> <select>
                        <option class="text-muted">Standard-Delivery- &euro;5.00</option>
                    </select>
                    <p>GIVE CODE</p> <input id="code" placeholder="Enter your code">
                </form>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    <div class="col text-right">{{ total }}</div>
                </div>
                {% if cart.get_mf_recommend %}
                <button type="button" class="btn btn-md my-0 p"  style="background-color: #929FBA; border-color: #929FBA; color: white" data-toggle="modal" data-target="#myModal">
                    CHECKOUT
                </button>
                <!-- 모달 영역 -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">How about this?</h4>
                                <button type="button" class="close right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&#10005;</span></button>
                            </div>
                            <div class="modal-body">
                                {% for i in cart.get_mf_recommend %}
                                <div class="row main align-items-center">
                                    {% if i.get_image_link %}
                                    {% if i.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
                                    <a class="col-2" href="{{i.get_absolute_url}}"><img class="img-item" src="{{i.get_image_link}}"></a>
                                    {% else %}
                                    <a class="col-2" href="{{i.get_absolute_url}}"><img class="img-item" src="{% static '/img/no_image.png' %}"></a>
                                    {% endif %}
                                    {% else %}
                                    <a class="col-2" href="{{i.get_absolute_url}}"><img class="img-item" src="{% static '/img/no_image.png' %}"></a>
                                    {% endif %}
                                    <a class="row" href="{{i.get_absolute_url}}">{{i | truncatechars:50}}</a>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-md my-0 p"  style="background-color: #929FBA; border-color: #929FBA; color: white">Go to checkout</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <button class="btn btn-md my-0 p"  style="background-color: #929FBA; border-color: #929FBA; color: white">CHECKOUT</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}