E-shop/shopping_mall/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<product_id>/', views.cart_delete, name='cart_delete'),
]

E-shop/shopping_mall/product/urls.py
from django.urls import path
from . import views

from django.conf.urls import url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.ProductList.as_view()),
    path('<str:pk>/', views.product_detail),
]

E-shop/shopping_mall/shopping_mall/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import logout, RegisterView,LoginView
from contact import views as contact_views
from mall.views import SearchFormView
from mall.views import MainView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mall.urls')),
    path('product/', include('product.urls')),
    path('logout/', logout),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('contact/', contact_views.contact_view, name='contact'),
    path('cart/', include('cart.urls')),
    path('search/', SearchFormView.as_view(), name='search'),
]
    

E-shop/shopping_mall/product/models.py
from django.db import models
from django.template.defaultfilters import slugify
from user.models import User
from mall.models import CategoryBig, CategoryMid, CategorySm, Brand

class Item(models.Model):
    asin = models.CharField(primary_key=True, max_length=100)
    price = models.FloatField(blank=True, null=True)
    enroll_date = models.DateField(blank=True, null=True)
    imagelink = models.TextField(db_column='imageLink', blank=True, null=True)  # Field name made lowercase.
    brand = models.ForeignKey(Brand, models.DO_NOTHING, blank=True, null=True)
    title = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    feature = models.TextField(blank=True, null=True)
    imagehighres = models.TextField(db_column='imageHighRes', blank=True, null=True)  # Field name made lowercase.
    cb = models.ForeignKey(CategoryBig, models.DO_NOTHING, blank=True, null=True)
    cm = models.ForeignKey(CategoryMid, models.DO_NOTHING, blank=True, null=True)
    cs = models.ForeignKey(CategorySm, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'item'


    def get_absolute_url(self):
        return f'/product/{self.pk}/'

    def get_image_link(self):
        imagelink = None
        if self.imagehighres:
            imagelink = self.imagehighres[1:-1].split(',')[0]
        return imagelink
    
    def __str__(self):
        return self.title

    def get_category(self):
        category = self.cb.name
        if self.cm.name != "None" and self.cm.name != "Extra":
            category += " > " + self.cm.name
        if self.cs.name != "None" and self.cs.name != "Extra":
            category += " > " + self.cs.name
        return category

    def get_brand(self):
        return self.brand.name
    
    def get_feature(self):
        return self.feature[1:-1]

    def get_also_view(self):
        item = Item.objects.get(pk=self.asin)
        also_asin = PreAlso.objects.get(asin=item.asin)
        
        also_view = []
        if also_asin.also_view:
            temp = also_asin.also_view[1:-1].split(",")
            also_view.extend(temp)
        if also_asin.also_buy:
            temp = also_asin.also_buy[1:-1].split(",")
            also_view.extend(temp)
        items = list(Item.objects.filter(asin__in=also_view))[:4]
        return items

    def get_rating_count(self):
        ratings = PreReview.objects.filter(asin=self.asin)
        return ratings.count()

    def get_rating_average(self):
        sum = 0
        ratings = PreReview.objects.filter(asin=self.asin)
        for i in ratings:
            sum += i.overall
        avg = sum / ratings.count()

        return avg

class PreReview(models.Model):
    review_id = models.AutoField(primary_key=True)
    overall = models.IntegerField()
    reviewtime = models.CharField(db_column='reviewTime', max_length=20, blank=True, null=True)  # Field name made lowercase.
    reviewerid = models.CharField(db_column='reviewerID', max_length=50)  # Field name made lowercase.
    asin = models.ForeignKey(Item, models.DO_NOTHING, db_column='asin')
    reviewtext = models.TextField(db_column='reviewText', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'pre_review'

class Review(models.Model):
    review_id = models.IntegerField(primary_key=True)
    reviewerid = models.ForeignKey(User, models.DO_NOTHING, db_column='reviewerID')  # Field name made lowercase.
    overall = models.IntegerField()
    reviewtext = models.TextField(db_column='reviewText', blank=True, null=True)  # Field name made lowercase.
    asin = models.ForeignKey(Item, models.DO_NOTHING, db_column='asin')
    reviewtime = models.CharField(db_column='reviewTime', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'review'


class PreAlso(models.Model):
    asin = models.ForeignKey(Item, models.DO_NOTHING, db_column='asin')
    also_id = models.AutoField(primary_key=True)
    also_view = models.TextField(blank=True, null=True)
    also_buy = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pre_also'

class ContentRecommend(models.Model):
    recommend_id = models.AutoField(primary_key=True)
    asin = models.ForeignKey('Item', models.DO_NOTHING, db_column='asin')
    recommend = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'content_recommend'

class Orders(models.Model):
    user_id = models.IntegerField(blank=True, null=True)
    asin = models.ForeignKey(Item, models.DO_NOTHING, db_column='asin')
    quantity = models.IntegerField(blank=True, null=True)
    reg_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'orders'

class AsinId(models.Model):
    aid = models.IntegerField(primary_key=True)
    asin = models.ForeignKey('Item', models.DO_NOTHING, db_column='asin', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'asin_id'

E-shop/shopping_mall/product/forms.py
from django import forms
# from .models import Product
'''
class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required':'상품명을 입력해주세요.'
        }, label="상품명", max_length=64)
    
    price = forms.IntegerField(
        error_messages={
            'required':"상품 가격을 입력해주세요."
        }, label="상품 가격",
    )
    description = forms.CharField(
        error_messages={
            'required':"상품 설명을 입력해주세요."
        }, label="상품 설명"
    )
    stock = forms.IntegerField(
        error_messages={
            'required':"재고를 입력해주세요."
        },label ="재고"
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stock = cleaned_data.get('stock')

        if not (name and price and description and stock):
            self.add_error('stock', '모든 값을 입력해야 합니다.')
'''

E-shop/shopping_mall/product/views.py
from re import I
import os
from django.shortcuts import render
from django.views.generic import ListView, FormView, DetailView
from django.utils.decorators import method_decorator
from user.decorator import login_required, admin_required
from rest_framework import generics, mixins
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Item, PreAlso, ContentRecommend, Review, AsinId
from user.models import User
from django.core.exceptions import ObjectDoesNotExist
from recommend import usercontent
import time

# Create your views here.

class ProductList(ListView):
    template_name = "product/list.html"
    model = Item
    context_object_name = "products"

    def get_queryset(self):
        product_all = Item.objects.all().order_by('-enroll_date')
        page = int(self.request.GET.get('p',1))
        paginator = Paginator(product_all, 9)
        queryset = paginator.get_page(page)
        return queryset

def product_detail(request, pk):
    item = Item.objects.get(pk=pk)
    recommends = []
    try:
        user = User.objects.get(email=request.session.get('user'))
        reviewes = Review.objects.filter(reviewerid=user)
        if reviewes:
            recommend = usercontent.load_content(reviewes, AsinId.objects.filter(asin=item.asin).values_list('aid')[0], user, item, num=4)
        else :
            recommend = ContentRecommend.objects.get(asin=item.asin).recommend[1:-1].split(",")
    except ObjectDoesNotExist:
        recommend = ContentRecommend.objects.get(asin=item.asin).recommend[1:-1].split(",")
        pass
    cnt = 0
    for r in recommend:
        if r == item.asin:
            continue
        cnt += 1
        recommends.append(Item.objects.get(asin=r))
        if cnt == 4:
            break
    
    return render(
        request, 'product/detail.html', 
        {
            'p': item,
            'recommends' : recommends,
        }
    )

E-shop/shopping_mall/product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>DAGO Mall</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static '/css/mdb.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">
  <link href="{% static '/css/detail.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
  {% block header %}
  {% endblock %}
</head>

<body>
  <!-- Navbar -->
  {% include 'mall/navbar.html' %}
  <!-- Navbar -->

  {% block main_area %}
  {% endblock %}

  <!--Footer-->
  {% include 'mall/footer.html' %}
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static '/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static '/js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

E-shop/shopping_mall/product/templates/product/detail.html
{% extends 'product/base.html' %}
{% load static %}
{% block main_area %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
        {% if p.get_image_link %}
          {% if p.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
            <img src="{{p.get_image_link}}" class="img-fluid" alt="">
          {% else %}
            <img src="{% static '/img/no_image.png' %}" class="img-fluid">
          {% endif %}
        {% else %}
          <img src="{% static '/img/no_image.png' %}" class="img-fluid">
        {% endif %}
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{p.get_category | truncatechars:45}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span>${{p.price}}</span>
            </p>

            <p class="lead font-weight-bold">{{p.title}}</p>
            <p>{{p.get_brand}}</p>
            <p>
              <a class="btn shadow-none border" data-toggle="collapse" href="#collapseFeature" role="button" aria-expanded="false" aria-controls="collapseFeature">
                 Click More Feature
              </a>
            </p>
            <div class="collapse" id="collapseFeature">
              <div class="mb-3">
                {{p.get_feature}}
              </div>
            </div>
<!--            <form method="POST" action="/order/create/" class="d-flex justify-content-left">-->
<!--              &lt;!&ndash; Default input &ndash;&gt;-->
<!--              {% csrf_token %}-->
<!--              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">-->
<!--              <button class="btn btn-md my-0 p" type="submit" style="background-color: #929FBA; border-color: #929FBA; color: white">Add to cart-->
<!--                <i class="fas fa-shopping-cart ml-1"></i>-->
<!--              </button>-->
<!--            </form>-->

            <div>
              {% if request.session.user %}
              <a class="btn btn-md my-0 p"  style="background-color: #929FBA; border-color: #929FBA; color: white" href="{% url 'cart:add_cart' p.asin %}">Add to Cart</a>
              {% else %}
              <a class="btn btn-md my-0 p"  style="background-color: #929FBA; border-color: #929FBA; color: white" href="/login/">Add to Cart</a>
              {% endif %}
            </div>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Section: Products v.3-->
      <div class="text mb-4" style="color: #929FBA">
        <h2>
          Recommend
        </h2>
      </div>
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          {% for i in recommends %}
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card h-100">
              <!--Card image-->
              <div class="view overlay">
              {% if i.get_image_link %}
                {% if i.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
                  <img src="{{i.get_image_link}}" class="card-img-top" alt="">
                {% else %}
                  <img src="{% static '/img/no_image.png' %}" class="card-img-top" alt="no_image">
                {% endif %}
              {% else %}
                <img src="{% static '/img/no_image.png' %}" class='card-img-top' alt="no_image">
              {% endif %}
                <a href="{{i.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <h5>
                  <strong>
                    <a href="{{i.get_absolute_url}}" class="dark-grey-text">{{i.title | truncatechars:20}}
                    </a>
                  </strong>
                </h5>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          {% endfor %}
          <!--Grid column-->
        </div>
      </section>

      {% if p.get_also_view %}
      <!--Section: Products v.3-->
      <div class="text mb-4" style="color: #929FBA">
        <h2>
          Also View
        </h2>
      </div>
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          {% for i in p.get_also_view %}
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card h-100">
              <!--Card image-->
              <div class="view overlay">
              {% if i.get_image_link %}
                {% if i.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
                  <img src="{{i.get_image_link}}" class="card-img-top" alt="">
                {% else %}
                  <img src="{% static '/img/no_image.png' %}" class="card-img-top" alt="no_image">
                {% endif %}
              {% else %}
                <img src="{% static '/img/no_image.png' %}" class='card-img-top' alt="no_image">
              {% endif %}
                <a href="{{i.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <h5>
                  <strong>
                    <a href="{{i.get_absolute_url}}" class="dark-grey-text">{{i.title | truncatechars:20}}
                    </a>
                  </strong>
                </h5>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          {% endfor %}
          <!--Grid column-->
        </div>
      </section>
      {% endif %}
      <!--Section: Products v.3-->
    </div>
  </main>
  <!--Main layout-->
{% endblock %}

E-shop/shopping_mall/product/templates/product/list.html
{% extends "product/base.html" %}
{% load humanize %}
{% block header %}
<script>
    function product_detail(id){
        $.ajax({
            url: "/api/product/" + id,
            success: function (result) {
                $("#product-"+id).popover({
                    html:true,
                    content: result.name + "<br>" + result.price + "원"
                }).popover('show');
            }
        });
    }

    function product_leave(id){
        $("#product-"+id).popover('hide');
    }
</script>
{% endblock %}
{% block main_area %}

{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Graduate">
	<link rel="stylesheet" href="{% static 'css/list_style.css' %}" />
	<title>DAGO Mall</title>
</head>
<div class="row mt-5">
    <div class="col-12 text-center">
        {{error}}
    </div>
</div>
<div class="container">
    <div class="row main-body">
        {% for product in products %}
        <div class="col-md-4 mt-2">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
<!--                        <img src={{ product.image_link }} class="card-img img-fluid" width="96" height="350" alt="">-->
                        <!--Card image-->
                        <div class="view overlay">
                            {% if product.get_image_link %}
                            {% if product.get_image_link != 'https://static.bhphoto.com/images/itemImgPlaceholder.jpg' %}
                            <img src="{{product.get_image_link}}" class="card-img-top-list" alt="">
                            {% else %}
                            <img src="{% static '/img/no_image.png' %}" class="card-img-top-list" alt="no_image">
                            {% endif %}
                            {% else %}
                            <img src="{% static '/img/no_image.png' %}" class='card-img-top-list' alt="no_image">
                            {% endif %}
                            <a href="{{product.get_absolute_url}}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                        <!--Card image-->
                    </div>
                </div>
                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h4 class="font-weight-semibold mb-2"> <a href="{{product.get_absolute_url}}" class="blue-text" data-abc="true" style="color:black;">{{product.title | truncatechars:70}}</a> </h4>
                        <a href="{{product.get_absolute_url}}" class="text-muted" data-abc="true">{{product.get_category | truncatechars:70}}</a>
                    </div>
                    <div><h6 class="mb-0 font-weight-semibold">{{product.get_brand}}</h6></div>
                    <div><h6 class="mb-0 font-weight-semibold">${{product.price}}</h6></div>
                    <div>
                        <i class="fa fa-star star"></i>
                        <script type="text/javascript">
                        var num = {{product.get_rating_average}};
                        for ( var i=0; i<num-1 ; i++) {
                        document.write("<i class=\"fa fa-star star\"></i>");
                        }
                        </script>
                    </div>
                    <div class="text-muted mb-3">{{product.get_rating_count}} reviews</div>
<!--                    <button type="button" class="btn bg-cart"><i class="fa fa-cart-plus mr-2"></i> Add to cart</button>-->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?p={{products.previous_page_number }}">이전으로</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">이전으로</a>
                    </li>
                    {% endif %}
<!--                    <li class="page-item">-->
<!--                        <a class="page-link" href="#">{{products.number}}/{{products.paginator.num_pages}}</a>-->
<!--                    </li>-->
                    {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">
                            <span class="sr-only">(current)</span>
                            {{ i }}
                        </a>
                    </li>
                    {% elif i > products.number|add:-3 and i < products.number|add:3 %}
                    <li class="page-item">
                        <a class="page-link" href="?p={{ i }}">{{ i }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?p={{products.next_page_number}}">다음으로</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">다음으로</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

E-shop/shopping_mall/product/templates/product/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/" target="_self">
      <strong class="blue-text">Da, GO!</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect active" href="/"><font size="3em" style="font-weight: 350;"> HOME </font>
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/contact/"><font size="3em" style="font-weight: 350;"> CONTACT </font></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="/product/"><font size="3em" style="font-weight: 350;"> PROUDCT </font></span></a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect">
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"><font size="3em" style="font-weight: 350;"> Cart </font>
              <span class="badge red z-depth-1"> 1 </span>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_self">
            <i class="fas fa-cog"></i>
            <span class="clearfix d-none d-sm-inline-block"><font size="3em" style="font-weight: 350;"> Settings  </font></span>
          </a>
        </li>
        <li class="nav-item">
<!--          <a href="/login/" class="nav-link waves-effect" target="_self">-->
<!--          <i class="fas fa-sign-in-alt"></i>-->
<!--            <span class="clearfix d-none d-sm-inline-block"><font size="3em" style="font-weight: 350;"> SIGN IN </font></span>-->
            {% if request.session.user %}
            <a href="/logout/" class="nav-link waves-effect" target="_self">
            <i class="fas fa-sign-in-alt"></i>
            <span class="clearfix d-none d-sm-inline-block"><font size="3em" style="font-weight: 350;">SIGN OUT</span>
            {% else %}
            <a href="/login/" class="nav-link waves-effect" target="_self">
            <i class="fas fa-sign-in-alt"></i>
            <span class="clearfix d-none d-sm-inline-block"><font size="3em" style="font-weight: 350;">SIGN IN</span>
            {% endif %}
          </a>
        </li>
      </ul>

    </div>

  </div>
</nav>

E-shop/shopping_mall/product/templates/product/register.html
{% extends "user/base.html" %}
{% block header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
<script>
        $(document).ready(function() {
            $('#id_description').summernote({
                height:300,
                placeholder:"상품 설명을 입력해주세요."
            });
        });
      </script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>상품 등록</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12 text-center">
        {{error}}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action=".">
            {% csrf_token %}
            {% for field in form %}
            {% ifequal field.name 'description' %}
            <div class="form-group">
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                <textarea class="form-control" id="{{field.id_for_label}}" name ="{{field.name}}" placeholder="{{field.label}}"></textarea>
            </div>
            {% else %}
            <div class="form-group">
                <label for="{{field.id_for_label }}">{{field.label}}</label>
                <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label}}" placeholder="{{field.label}}" name="{{field.name}}"/>
            </div>
            {% endifequal %}
            {% if field.errors %}
            <span style="color:red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">상품 등록</button>
        </form>
    </div>
</div>
{% endblock %}